#version: '3.0' # docker compose version -> delete, 2.25.0 이상부터는 version 필요 없음

services: # container setting info
    mysql-docker:
      container_name: mysql-container
      image: mysql:8.0
      volumes:
        - db-mysql:/var/lib/mysql
      restart: unless-stopped
      environment:
        - MYSQL_ROOT_PASSWORD=jamjam
        - MYSQL_DATABASE=jamjam
        - MYSQL_USER=jamjam
        - MYSQL_PASSWORD=jamjama604
      networks:
        - db-network
      ports:
        - "3306:3306"
    redis-docker:
      container_name: redis-container
      image: redis:7.0
      ports:
        - "6379:6379"
      volumes:
        - db-redis:/var/lib/redis
      networks:
        - db-network

volumes:
  db-mysql:
  db-redis:


networks:
  db-network:
    driver: bridge

