server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  logging:
    level:
      com.app: debug
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
  redirect:
    uri: ${KAKAO_REDIRECT_URI}

openvidu:
  openvidu-url: ${OPENVIDU_URL:http://localhost:4443/}
  openvidu-secret: ${OPENVIDU_SECRET:MY_SECRET}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

token:
  secret: ${TOKEN_CLIENT_SECRET}
  access-token-expiration-time: ${ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}

#logging:
#  level:
#    root: DEBUG

otp:
  user:
    client:
      url: ${OTP_USER_CLIENT_URL}

google:
  directions:
    api:
      url: ${GOOGLE_DIRECTIONS_API_URL}
      key: ${GOOGLE_DIRECTIONS_API_KEY}