"""empty message

Revision ID: 238b2d08e2bd
Revises: 7ea725afbe60
Create Date: 2024-07-23 17:26:52.664212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238b2d08e2bd'
down_revision = '7ea725afbe60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_tb', sa.Column('subway_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_tb', 'subway_name')
    # ### end Alembic commands ###
