"""empty message

Revision ID: 3c48ca8dfc45
Revises: 
Create Date: 2024-08-11 16:46:10.642574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c48ca8dfc45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_info',
    sa.Column('local_info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('road_address', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('local_info_id')
    )
    op.create_index('ix_station_name_category', 'local_info', ['station_name', 'category'], unique=False)
    op.drop_table('member')
    op.drop_table('round_record')
    op.drop_table('member_round_record')
    op.drop_table('game_record')
    op.drop_index('UKd5t8ashijbtbtixpivsqn7iva', table_name='attendee')
    op.drop_table('attendee')
    op.drop_table('chatting')
    op.drop_table('game')
    op.drop_table('board')
    op.drop_index('UKik57ksdejdd1k28sscylwx9y1', table_name='room')
    op.drop_index('UKivbf4ub75t1o6muhmnyk9kv8x', table_name='room')
    op.drop_table('room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('room_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('ended_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('meeting_date', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('purpose', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('start', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('attendee_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('roomuuid', sa.BINARY(length=16), nullable=False),
    sa.Column('room_status', mysql.ENUM('ABORTED', 'CREATED', 'FINISHED', 'ONGOING'), nullable=True),
    sa.Column('root_attendee_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee.attendee_id'], name='FK79x1wd24yq9y92rscfecddyou'),
    sa.ForeignKeyConstraint(['root_attendee_id'], ['attendee.attendee_id'], name='FKjt6b766ts4avxwplm69uj85va'),
    sa.PrimaryKeyConstraint('room_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('UKivbf4ub75t1o6muhmnyk9kv8x', 'room', ['roomuuid'], unique=True)
    op.create_index('UKik57ksdejdd1k28sscylwx9y1', 'room', ['root_attendee_id'], unique=True)
    op.create_table('board',
    sa.Column('board_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('author', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('board_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('game',
    sa.Column('game_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('difficulty', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_use', mysql.BIT(length=1), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('game_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chatting',
    sa.Column('chatting_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('attendee_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('room_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee.attendee_id'], name='FK8urbwpnjg2g5l4b47gi4vsry7'),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], name='FK13pr0n94bi1bp3a6r966l52kr'),
    sa.PrimaryKeyConstraint('chatting_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('attendee',
    sa.Column('attendee_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('lat', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('lon', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('member_round_record_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('room_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('attendeeuuid', sa.BINARY(length=16), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('attendee_status', mysql.ENUM('ENTERED', 'EXITED', 'WAITING'), nullable=True),
    sa.Column('duration', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('profile_image_url', mysql.ENUM('PROFILE1', 'PROFILE10', 'PROFILE11', 'PROFILE12', 'PROFILE2', 'PROFILE3', 'PROFILE4', 'PROFILE5', 'PROFILE6', 'PROFILE7', 'PROFILE8', 'PROFILE9'), nullable=True),
    sa.Column('route', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name='FK619wqniayj978imllxjppas22'),
    sa.ForeignKeyConstraint(['member_round_record_id'], ['member_round_record.member_round_record_id'], name='FKlx77b0sd9pua7ghppsaolk1la'),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], name='FKf3q2rgffy21a1lxpede9pj8rb'),
    sa.PrimaryKeyConstraint('attendee_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('UKd5t8ashijbtbtixpivsqn7iva', 'attendee', ['attendeeuuid'], unique=True)
    op.create_table('game_record',
    sa.Column('game_record_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('final_station_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('round_cnt', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], name='FK7ng0p57cddwjtpiyjsns9pmjh'),
    sa.PrimaryKeyConstraint('game_record_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('member_round_record',
    sa.Column('member_round_record_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('is_play', mysql.BIT(length=1), nullable=True),
    sa.Column('round_record_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['round_record_id'], ['round_record.round_record_id'], name='FK7n9ds9mk3kbwxvkkvxoxavbl7'),
    sa.PrimaryKeyConstraint('member_round_record_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('round_record',
    sa.Column('round_record_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('ended_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('round', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('station_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('game_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.Column('game_record_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], name='FKmj2jr62nuy8n6f097gclqmi55'),
    sa.ForeignKeyConstraint(['game_record_id'], ['game_record.game_record_id'], name='FK1niaismmns97lgjijx1kwiico'),
    sa.PrimaryKeyConstraint('round_record_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('member',
    sa.Column('member_id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('profile', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('provider', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('provider_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('refresh_token', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('token_expiration_time', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('member_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index('ix_station_name_category', table_name='local_info')
    op.drop_table('local_info')
    # ### end Alembic commands ###
