"""empty message

Revision ID: 4f70c804be50
Revises: 238b2d08e2bd
Create Date: 2024-07-23 17:55:55.050005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f70c804be50'
down_revision = '238b2d08e2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_tb', sa.Column('create_at', sa.DateTime(), nullable=True))
    op.add_column('place_tb', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_tb', 'update_at')
    op.drop_column('place_tb', 'create_at')
    # ### end Alembic commands ###
