"""empty message

Revision ID: 7ea725afbe60
Revises: 1da80764425e
Create Date: 2024-07-23 17:19:19.455825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea725afbe60'
down_revision = '1da80764425e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('place_tb', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('place_tb', 'is_delete')
    # ### end Alembic commands ###
