version: '3'
services:
  database:
    container_name: jamjam_mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_ROOT_HOST=%
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./docker/data:/var/lib/mysql
    restart: always
    networks:
      - test_network

  application:
    container_name: jamjam_spring
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${SPRING_HOST}:${SPRING_HOST}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - database
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
