version: '3.1'

services:
  flask-app:
    container_name: flask-container
    image: ln8847/flask-app:1.0
    ports:
      - "5100:5100"
    environment:
      - TZ=Asia/Seoul  # timezone 설정 부분
    networks:
      - shared-network

networks:
  shared-network:
    external: true
